# Generated by Django 4.2.3 on 2023-07-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
