# Generated by Django 4.2.3 on 2023-07-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_labels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
